### ISSUE TITLE
Replace broccoli-sass with broccoli-sass-source-maps

### ISSUE THREAD

**Issue by corbinu** [glimmerjs/glimmer-application-pipeline#104]
Hey,

I was hoping that broccoli-sass could be replaced with broccoli-sass-source-maps. broccoli-sass is still on node-sass ^3.x.x which does not have prebuilt binaries for Node 8

**Comment by rwjblue** [comment]
On master, broccoli-sass is only used in a fallback with a deprecation that instructs you to use ember-cli-sass.  It hasn't been released yet due to other changes that are in the pipeline..

**Comment by corbinu** [comment]
can it be moved to an option dep then? the issue is not it's use but the time to compile on npm install

**Comment by corbinu** [comment]
This is still any issue in the latest version as broccoli-sass is still a dependency. node-sass ends up getting rebuild everytime npm install is run. (wouldn't be such an issue if sass wasn't a very big project to build. I am happy to open a PR

**Comment by Turbo87** [comment]
@rwjblue given that those "other changes" have been released by now can we remove the dependency and the deprecated code now?

the time that `ember new my-app -b @glimmer/blueprint` takes is ridiculous due to the build time of `node-sass@3` and made me run with `--skip-npm` to figure out why it was taking minutes to complete.
