### ISSUE TITLE
Make web components work with minification (i.e. `ember b --prod`)

### ISSUE THREAD

**Issue by robbiepitts** [glimmerjs/glimmer-application-pipeline#48]
I wanted to start this discussion about forking broccoli-uglify-sourcemap because @glimmer/web-component breaks app production builds. This is because the release versions of Uglify cannot handle ES2015+, so we need to use the Uglify harmony branch. Only problem is, we do not know stable/baked this is (building and running a basic app was successful).

So, is this something I should get rolling on? Do we just compile to ES5 and tell people to get the polyfill? Is there a better solution somebody can think of?

**Comment by robbiepitts** [comment]
Bump

cc @rwjblue @dgeb @tomdale @Turbo87

**Comment by Turbo87** [comment]
I'm a little worried about using a forked thing here. Would it be possible to convince the uglify maintainers to publish alpha/beta versions of their harmony branch?

**Comment by rwjblue** [comment]
Seems like a good thing to ask, if the answer is no we can still do whatever we want but it would be nice to have the "real" think published...

**Comment by robbiepitts** [comment]
Okay, so I got a reply from @finom (thanks!) which led me to this: https://github.com/mishoo/UglifyJS2/issues/448#issuecomment-290391043. Even if they were willing to publish an alpha it sounds like it might not be baked enough for us.

I'm thinking now plan b might be compiling to es5 and bundling in the polyfill or shipping it with the web component blueprint.

**Comment by cibernox** [comment]
Just today because [this issue](https://github.com/ember-cli/rfcs/issues/104) I brought this topic for ember itself. Seems that babili is the only fully ES6 capable uglifier, and by it's nature (a babel preset) it is naturally up to date with the latest development of the spec.

In some benchmarks seems that uglify compresses marginally better than babili, but I think that ES6 support is probably worthy. See https://github.com/kanongil/ember-cli-babili

Another option could be the google closure compiler.

**Comment by Turbo87** [comment]
Just FYI in my initial tests I had not been able to make input source maps work with babili. Closure compiler wasn't particularly happy with the output of babel and printed out lots of warnings and errors.

**Comment by robbiepitts** [comment]
Current status: I'm working on a PR in application-pipeline that does the following:

- Backs out the babel bypass for web-component
- Includes the [native-shim polyfill](https://github.com/webcomponents/custom-elements/blob/master/src/native-shim.js) by default for apps with the web-component package installed
- Provides an option for manually setting which polyfill (or no polyfill) to use, basically `'custom-elements' | 'native-shim' | null` ([custom-elements polyfill](https://github.com/webcomponents/custom-elements/blob/master/custom-elements.min.js))

**Comment by tomdale** [comment]
I'm not excited about baking in a Web Components polyfill since the entire point of having a separate package is to decouple the concerns. Hardcoding fixes into the build pipeline inherently privileges our own packages, and unlocking experimentation is what we're trying to do in the first place!

I wonder if @rwjblue's work on the build pipeline allows the web components package to deal with this itself?

**Comment by robbiepitts** [comment]
> Hardcoding fixes into the build pipeline inherently privileges our own packages, and unlocking experimentation is what we're trying to do in the first place!

Very good point @tomdale. It did rub me the wrong way a bit but we're sort of between a rock and a hard place with this and didn't know what else to do. I'll await @rwjblue's response.

**Comment by rwjblue** [comment]
@robbiepitts - I believe that this is resolved now?

**Comment by robbiepitts** [comment]
Yep!
